apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "geostreams.fullname" . }}-api
  labels:
    app.kubernetes.io/name: {{ include "geostreams.fullname" . }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "geostreams.fullname" . }}-api
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "geostreams.fullname" . }}-api
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "geostreams.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
{{/*      initContainers:*/}}
{{/*        - name: check-postgresql*/}}
{{/*          image: "ncsa/checks:1.0.0"*/}}
{{/*          env:*/}}
{{/*            - name: PG_URI*/}}
{{/*              value: {{ include "geostreams.postgresqluri" . }}*/}}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /geostreams
              port: http
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: custom-volume
              mountPath: /home/geostreams/conf
          env:
            - name: APPLICATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: geostreams-secret
      volumes:
        - name: custom-volume
          configMap:
            name: {{ include "geostreams.fullname" . }}-config
            items:
              - key: application.conf
                path: application.conf
              - key: logback.xml
                path: logback.xml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
