apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geostreams.fullname" . }}
  labels:
{{ include "geostreams.labels" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.secretKey }}
  geostreams-secret:  {{ .Values.secretKey | b64enc | quote }}
  {{- else }}
  geostreams-secret: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}