apiVersion: v1
kind: Service
metadata:
  name: {{ include "geostreams.fullname" . }}-api
  labels:
{{- include "geostreams.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "geostreams.fullname" . }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "geostreams.fullname" . }}-geodashboard
  labels:
{{- include "geostreams.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.geodashboard.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "geostreams.fullname" . }}-geodashboard
    app.kubernetes.io/instance: {{ .Release.Name }}
